<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <NoWarn>
      CA1062 <!--Validate arguments of public methods-->;
      CA1707 <!--Identifiers should not contain underscores-->;
    </NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Soenneker.Utils.AutoBogus" Version="3.0.805" />
    <PackageReference Include="Meziantou.Extensions.Logging.Xunit" Version="1.0.18" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Testcontainers" Version="4.7.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\mmazur.YnabApiClient\mmazur.YnabApiClient.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="open_api_spec.yaml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>