<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <NoWarn>
      CA1062 <!--Validate arguments of public methods-->;
      CA1707 <!--Identifiers should not contain underscores-->;
    </NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Soenneker.Utils.AutoBogus" />
    <PackageReference Include="Meziantou.Extensions.Logging.Xunit" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Testcontainers" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\mmazur.YnabApiClient\mmazur.YnabApiClient.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="open_api_spec.yaml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>