namespace mmazur.YnabApiClient.V1.Transactions;

public interface IYnabV1ScheduledTransactionApiClient
    : IYnabV1ScheduledTransactionGetApiClient, IYnabV1ScheduledTransactionUpdateApiClient, IYnabV1ScheduledTransactionDeleteApiClient;